# 1º PRUEBA VGG16

02/01/2023 -> NO FUNCIONA PORQUE EL FORMATO DE ARRAYS DE LAS IMÁGENES NO ES VÁLIDO, NO HE PODIDO CONVERTIRLO A TENSORES SIN OBTENER ALGÚN ERROR

https://www.enmilocalfunciona.io/deep-learning-basico-con-keras-parte-3-vgg/

In [56]:
import os
import skimage
import tensorflow as tf
import numpy as np
import cv2
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras import layers
from tensorflow.keras import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import plot_model
from tensorflow.keras import backend as K
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical

**DATOS PARA ENTRENAR -> OCT**

In [4]:
path_oct_train = "Datos EMD/OCT/TRAIN"

In [5]:
nombres_oct = os.listdir(path_oct_train)

In [11]:
print(nombres_oct)

['118741TD.jpg', '118741TI.jpg', '120948TD.jpg', '120948TI.jpg', '126661TD.jpg', '126661TI.jpg', '141770TD.jpg', '141770TI.jpg', '158979TD.jpg', '158979TI.jpg', '170692TD.jpg', '170692TI.jpg', '175999TD.jpg', '175999TI.jpg', '198336TD.jpg', '198336TI.jpg', '205809TD.jpg', '205809TI.jpg', '207852TD.jpg', '207852TI.jpg', '213529TD.jpg', '213529TI.jpg', '223185TD.jpg', '223185TI.jpg', '224007TD.jpg', '224007TI.jpg', '238098TD.jpg', '238098TI.jpg', '250413TD.jpg', '250413TI.jpg', '252193TD.jpg', '252193TI.jpg', '254998TD.jpg', '254998TI.jpg', '25683TD.jpg', '25683TI.jpg', '264526TD.jpg', '264526TI.jpg', '267428TD.jpg', '267428TI.jpg', '273006TD.jpg', '273006TI.jpg', '278146TD.jpg', '278146TI.jpg', '289215TD.jpg', '289215TI.jpg', '292557TD.jpg', '292557TI.jpg', '305021TD.jpg', '305021TI.jpg', '310482TD.jpg', '310482TI.jpg', '32094TD.jpg', '32094TI.jpg', '323220TD.jpg', '323220TI.jpg', '329658TD.jpg', '329658TI.jpg', '330782TD.jpg', '330782TI.jpg', '334488TD.jpg', '334488TI.jpg', '338760TD.j

Obtener las imágenes como tensor:

https://www.tensorflow.org/api_docs/python/tf/image/convert_image_dtype

In [64]:
train_ds = []

for e in nombres_oct:
    img = skimage.io.imread(path_oct_train+'/'+e)
    tensor_img = tf.image.convert_image_dtype(img,  dtype=tf.int64, saturate=False, name=None)
    train_ds.append(tensor_img)

In [66]:
train_ds = tf.convert_to_tensor(train_ds)

In [67]:
print(train_ds)

tf.Tensor(
[[[[ 36028797018963968  36028797018963968 108086391056891904]
   [ 36028797018963968  36028797018963968 108086391056891904]
   [ 36028797018963968  36028797018963968 108086391056891904]
   ...
   [ 36028797018963968  36028797018963968  36028797018963968]
   [ 36028797018963968  36028797018963968  36028797018963968]
   [ 36028797018963968  36028797018963968  36028797018963968]]

  [[ 36028797018963968  36028797018963968 108086391056891904]
   [ 36028797018963968  36028797018963968 108086391056891904]
   [ 36028797018963968  36028797018963968 108086391056891904]
   ...
   [ 36028797018963968  36028797018963968  36028797018963968]
   [ 36028797018963968  36028797018963968  36028797018963968]
   [ 36028797018963968  36028797018963968  36028797018963968]]

  [[ 36028797018963968  36028797018963968 108086391056891904]
   [ 36028797018963968  36028797018963968 108086391056891904]
   [ 36028797018963968  36028797018963968 108086391056891904]
   ...
   [ 36028797018963968  3602879701

In [68]:
#img = skimage.io.imread(path_oct_train+'/'+nombres_oct[0])

#print(tf.image.convert_image_dtype(img,  dtype=tf.int64, saturate=False, name=None))

In [69]:
#tf.image.convert_image_dtype(img, dtype=tf.int64, saturate=False, name=None)

In [19]:
train_labels = []

for e in nombres_oct:
    if e in os.listdir("Datos EMD/OCT/NO EMD"): #0 significa no EMD
        train_labels.append(0)
    elif e in os.listdir("Datos EMD/OCT/EMD"): #1 SIGNIFICA EMD
        train_labels.append(1)

In [20]:
tensor_train_labels = tf.convert_to_tensor(train_labels)

In [32]:
print(tensor_train_labels)

tf.Tensor(
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0
 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0
 0 0 0 0 0], shape=(116,), dtype=int32)


In [33]:
print(len(train_labels)==len(train_ds))

True


**DATOS PARA TEST -> IPhone**

In [78]:
path_iphone_test = "Datos EMD/OCT/TRAIN"

In [79]:
nombres_iphone = os.listdir(path_iphone_test)

In [80]:
test_ds = []

for e in nombres_iphone:
    img = skimage.io.imread(path_iphone_test+'/'+e)
    tensor_img = tf.image.convert_image_dtype(img,  dtype=tf.int64, saturate=False, name=None)
    test_ds.append(tensor_img)

In [81]:
test_ds = tf.convert_to_tensor(test_ds)

ResourceExhaustedError: {{function_node __wrapped__Pack_N_116_device_/job:localhost/replica:0/task:0/device:CPU:0}} OOM when allocating tensor with shape[116,1934,1960,3] and type int64 on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:Pack] name: packed

In [73]:
print(test_ds)

[<tf.Tensor: shape=(2176, 2176, 4), dtype=int64, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)>, <tf.Tensor: shape=(2176, 2176, 4),

In [40]:
test_labels = []

for e in nombres_iphone:
    if e in os.listdir("Datos EMD/iPhone/NO EMD"):
        test_labels.append(0)
    elif e in os.listdir("Datos EMD/iPhone/EMD"):
        test_labels.append(1)

In [41]:
tensor_test_labels = tf.convert_to_tensor(test_labels)

In [44]:
print(tensor_test_labels)

tf.Tensor(
[0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0
 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 0
 0], shape=(112,), dtype=int32)


In [42]:
print(len(test_labels)==len(test_ds))

True


**REDIMENSIONAR LAS IMÁGENES**

In [50]:
train_ds = tf.image.resize(train_ds, (150, 150))
test_ds = tf.image.resize(test_ds, (150, 150))

InvalidArgumentError: {{function_node __wrapped__Pack_N_106_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shapes of all inputs must match: values[0].shape = [2176,2176,4] != values[2].shape = [2172,2172,4] [Op:Pack] name: images

**CONSTRUIR UNA MATRIZ PARA ALBERGAR LAS LABELS**

In [51]:
train_labels = to_categorical(train_labels, num_classes=2)
test_labels = to_categorical(test_labels, num_classes=2)

**CONSTRUCCIÓN DEL MODELO**

In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input

## Loading VGG16 model
base_model = VGG16(weights="imagenet", include_top=False, input_shape=train_ds[0].shape)
base_model.trainable = False ## Not trainable weights

## Preprocessing input
train_ds = preprocess_input(train_ds) 
test_ds = preprocess_input(test_ds)

In [ ]:
base_model.summary()